
package Interfaces;

public class GeneralMenu extends javax.swing.JFrame {
NewtonRaphson n = new NewtonRaphson();
    /**
     * Creates new form GeneralMenu
     */
    public GeneralMenu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MetBiss = new javax.swing.JButton();
        MetFP = new javax.swing.JButton();
        MEtGraf = new javax.swing.JButton();
        MetIPF = new javax.swing.JButton();
        MetNR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbselect = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANALISIS NUMERICO 2018");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MetBiss.setText("Metodo Biseccion");
        MetBiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetBissActionPerformed(evt);
            }
        });
        getContentPane().add(MetBiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        MetFP.setText("Metodo Falsa Posicion");
        MetFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetFPActionPerformed(evt);
            }
        });
        getContentPane().add(MetFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        MEtGraf.setText("Metodo Grafico");
        getContentPane().add(MEtGraf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        MetIPF.setText("Metodo Iteracion de Punto Fijo");
        MetIPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetIPFActionPerformed(evt);
            }
        });
        getContentPane().add(MetIPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        MetNR.setText("Metodo Newton Raphson");
        MetNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetNRActionPerformed(evt);
            }
        });
        getContentPane().add(MetNR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ANALISIS NUMERICO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 20));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_active__no.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 0, 40, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¿Con que metodo desea calcular la raiz?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        cmbselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccione Ecuacion--", "1", "2", "3", "4", "5" }));
        getContentPane().add(cmbselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-negro.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void MetBissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetBissActionPerformed
        n.show();
        this.show(false);
    }//GEN-LAST:event_MetBissActionPerformed

    private void MetFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetFPActionPerformed
        
        n.show();
        this.show(false);
    }//GEN-LAST:event_MetFPActionPerformed

    private void MetNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetNRActionPerformed
        n.show();
        this.show(false);
    }//GEN-LAST:event_MetNRActionPerformed

    private void MetIPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetIPFActionPerformed
        n.show();
        this.show(false);
    }//GEN-LAST:event_MetIPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MEtGraf;
    private javax.swing.JButton MetBiss;
    private javax.swing.JButton MetFP;
    private javax.swing.JButton MetIPF;
    private javax.swing.JButton MetNR;
    private javax.swing.JComboBox cmbselect;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
